name = "learnwisp"
version = "1.0.0"
description = "A collection of Wisp examples"

[dependencies]
wisp = ">= 1.8.0 and < 2.0.0"
mist = ">= 5.0.3 and < 6.0.0"
gleam_stdlib = ">= 0.62.1 and < 1.0.0"
gleam_erlang = ">= 1.3.0 and < 2.0.0"
gleam_http = ">= 4.1.1 and < 5.0.0"
gleam_json = ">= 3.0.2 and < 4.0.0"
gleam_crypto = ">= 1.5.1 and < 2.0.0"
gsv = ">= 5.0.0 and < 6.0.0"

[dev-dependencies]
gleeunit = ">= 1.6.1 and < 2.0.0"
